import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const statePath = join(repoRoot, 'docs', 'handoff-state.json')
const outputPath = join(repoRoot, 'docs', 'next-session.md')

function run(command, args, fallback = 'unavailable') {
  try {
    return execFileSync(command, args, {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    }).trim()
  } catch {
    return fallback
  }
}

function bulletList(items) {
  return items.map((item) => `- ${item}`).join('\n')
}

function numberedList(items) {
  return items.map((item, index) => `${index + 1}. ${item}`).join('\n')
}

function codeBlock(language, content) {
  return `\`\`\`${language}\n${content}\n\`\`\``
}

const state = JSON.parse(readFileSync(statePath, 'utf8'))
const now = new Intl.DateTimeFormat('sv-SE', {
  timeZone: 'Asia/Shanghai',
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
  hour: '2-digit',
  minute: '2-digit',
  second: '2-digit',
  hour12: false,
}).format(new Date())

const branchStatus = run('git', ['status', '--short', '--branch'])
const recentCommits = run('git', ['log', '--oneline', '--decorate', '-5'])
const latestCommit = run('git', ['log', '-1', '--oneline'])
const remotes = run('git', ['remote', '-v'])
const packageJson = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'))
const scripts = Object.entries(packageJson.scripts ?? {})
  .map(([name, command]) => `- \`${name}\`: \`${command}\``)
  .join('\n')

const content = `# Next Session Handoff

Updated: ${now} Asia/Shanghai
Generated by: \`${state.updatedBy}\`

## Resume Protocol

When a new Codex session starts in this repository:

1. Read \`AGENTS.md\`.
2. Read this file.
3. Skim \`docs/devlog.md\`.
4. Run \`git status --short --branch\` and compare with the snapshot below.
5. If the user says "continue" or gives a new Claude Sprout requirement, continue from "Next Tasks" unless newer user instructions override it.

## Git Snapshot

Latest commit at generation time:

${codeBlock('text', latestCommit)}

Branch status at generation time:

${codeBlock('text', branchStatus)}

Recent commits:

${codeBlock('text', recentCommits)}

Remotes:

${codeBlock('text', remotes)}

## Current State

${bulletList(state.currentState)}

## Implemented So Far

${bulletList(state.implemented)}

## Verification Commands

Known passing commands:

${codeBlock('powershell', state.knownPassingCommands.join('\n'))}

Package scripts:

${scripts}

Run the desktop exe:

${codeBlock('powershell', state.runCommands[0])}

Run the dev preview:

${codeBlock('powershell', state.runCommands[1])}

Pet preview route:

${codeBlock('text', state.petPreviewUrl)}

## Known Blockers

${bulletList(state.knownBlockers)}

## Next Tasks

${numberedList(state.nextTasks)}

## Important Decisions

${bulletList(state.importantDecisions)}

## Update Mechanism

This file is generated from \`docs/handoff-state.json\` plus live git/package metadata.

Use:

${codeBlock('powershell', 'npm run handoff:update')}

Optional local automation:

${codeBlock('powershell', 'npm run hooks:install')}

The installed git pre-commit hook runs \`npm run handoff:update\` and stages \`docs/next-session.md\` automatically before each commit.
`

writeFileSync(outputPath, content, 'utf8')
console.log(`Updated ${outputPath}`)
